<a href="https://colab.research.google.com/github/Suhrobjonibodullayev/ML-Learning-Journey/blob/main/03_pandas_basics/pandas_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Pandas**

https://pandas.pydata.org/docs/user_guide/10min.html

https://www.tutorialspoint.com/python_pandas/index.htm

https://jakevdp.github.io/PythonDataScienceHandbook/

In [ ]:
import numpy as np
import pandas as pd

Pandas --> Series-1D DataFrame-2D Panel-3d Malumot tuzilmalariga ega.

## Series - bir o'lchovli arrayga o'xshash index va qiymatdan iborat ustun.

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8]) # series yaratish

s.values # qiymatlar
s.index # indexlar

s[0] # index orqali qiymatni ko'rish

data = np.array(['a','b','c','d'])
c = pd.Series(data,index=[100,101,102,103]) # indexni o'zimiz berishimiz mumkin.

s.name = 'sonlar' # seriesga nom berish
s.index.name = 'indeks' # index ustuniga nom berish

s[6] = 3.5 # yangi qiymat qo'shish

del s[6] # 6 indexdagi elementni o'chirish

s[:3] # bir nechta qiymatlarni ko'rish

s[s>2] # saralash

data = {'a' : 0., 'b' : 1., 'c' : 2.} # dict dan Series yaratish
v = pd.Series(data)

s.isnull() # Nan qiymatga true qaytaradi
s.notnull() # Nan qiymatga False qaytaradi

s.hasnans # series ichida Nan qiymat borligini tekshiradi

s.is_unique # series ichida qiymatlar takrorlanmas ekanligini tekshiradi

s.shape
s.size

s.min()
s.max()
s.mean()

s.iloc[-1] # Seriesga index tartib raqami bo'yicha murojat etish

v.loc['a'] # seriesga index nomi bo'yicha murojat etish

v.to_numpy() #Seriesni Numpy qilish

pd.Series(range(3), index=list("abc"), name="ser")

a    0
b    1
c    2
Name: ser, dtype: int64

## DataFrame - tartibli ustunlardan iborat 2 o'lchovli jadval ko'rinishidgi malumotlar tuzilmasi.

In [ ]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       "Temp":[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53]} # dict orqali DataFrame yaratish

df = pd.DataFrame(data,columns=['Yil','Temp','Aholi soni','YAIM'], index=[21,20,19,18,17,16,15,10]) # columns (ustunlar) va indexga qiymat berish

df.head() # nechtaligi aytilmasa boshidagi 5 ta qatorni chiqaradi
df.tail(3) # nechtaligi aytilmasa oxiridagi 5 ta qatorni chiqaradi

df.Temp # DataFrame --> Series ko'rinishida chiqadi
df['Aholi soni']

df[['Aholi soni']] # DataFrame --> DataFrame ko'rinishida ajratib olish
df[['Aholi soni','Yil']]

#yangi ustunni elementlar bilan to'ldirish

df["YAIM"] = 16000 # hammasiga bir xil qiymat berish
val = pd.Series([1750, 1560, 1270], index=[21, 18, 10])
df.YAIM = val # maulum indexlarga qiymat berish

YAIM = [1700, 1670, 1600, 1590, 1400, 1300, 1350, 1360]
df['YAIM'] = YAIM # hamma indexga mos qiymat berish

df['1500+'] = df['YAIM'] > 1500 # shartli ustun yaratish
del df['1500+'] # ustunni o'chirish
df

data = {
    'Uzbekistan':{2021:33.9, 2020:33.5, 2019:32.9, 2018:32.5, 2017:31.9},
    'Kazakhstan':{2021:18.9, 2020:18.7, 2019:18.5, 2018:18.3, 2017:18.1, 2016:17.8}
}
df2 = pd.DataFrame(data)
df2.index.name = "Yil" # indexga nom berish

df2 = pd.DataFrame(data, index=[2021, 2019, 2017]) # 2021, 2019 va 2017 yil ma'lumotlarini olamiz

df2.T # transpose(ustun va qatorlar o'rnini almashtirish) qilish

            2021  2019  2017
Uzbekistan  33.9  32.9  31.9
Kazakhstan  18.9  18.5  18.1

Index bilan ishlash

In [ ]:
indeks = df2.index # index objectini aloxida saqlash mumkin , u o'zgarmas bo'ladi
indeks[1] #tartib raqam bo'yicha murojat qilish mumkin

df2.columns # columns ni ko'rish

'Tajikistan' in df2.columns # tekshirish
2020 in df2.index # index takrorlanuvchi qiymatga ega bo'lishi mumkin.

usernames = {"anvar":"anvarbek223", "olim":"olimtoy", "maryam":"mary334455","javohir":"javohir445"}
emails = {"anvar":"anvar@gmail.com", "olim":"olim@mail.ru", "maryam":"mary33@gmail.com","javohir":"javohir445@gmail.com"}

data = {
    'username':usernames,
    'email':emails
}
df2 = pd.DataFrame(data)

# dfus.set_index('yil', inplace=True)
newind = pd.Index(['olim','nafisa','hamida']) # yangi indeks yaratamiz

newind.isin(df2.index) # newind df2.index tarkibida borligni tekshirish
df2.index.difference(newind) # df2 farqi
df2.index.union(newind) # 2 indexni birlashtirish

df2.index.delete(0) # index tartib raqimi bo'yicha o'chirish
df2.index.drop('olim') # index nomi bo'yicha 1 kelganni o'chiradi

df2.index.insert(2,'masha') # 5-o'ringa mashani qo'shamiz

df2.index.is_unique
df2.index.is_numeric
df2.index.is_monotonic_decreasing

df2.index.unique() # noyob (takrorlanmas) elementlar

Index(['anvar', 'olim', 'maryam', 'javohir'], dtype='object')

In [ ]:
data = {'Yil':[2021, 2020, 2019, 2018, 2017, 2016, 2015, 2010],
       'Aholi soni':[33.9, 33.5, 32.9, 32.5, 31.9, 31.4, 30.9, 28.5],
       'Temp':[1.54, 1.48, 1.56, 1.62, 1.65, 1.66, 1.64, 1.53],
       'Zichlik':[79.77, 78.68, 77.53, 76.34, 75.13, 73.91, 72.71, 67.03]}
df = pd.DataFrame(data)
df.index = [21, 20, 19, 18, 17, 16, 15, 10]

# .reindex() indekslar o'rnini almashtirish

df.reindex([10,15,20])

df.reindex(index=range(10,22), method="nearest") # method='ffill' .reindex yordamida yangi indekslar qo'shish va ularni turli usullar (method) yordamida to'ldirish

df.reindex(columns=['Aholi soni','Temp']) #  ustunlarni qayta indekslash

df.loc[[10,15,20],['Aholi soni','Temp']] #.loc yordamida indekslash .loc yordamida qator va ustunlani ularning nomi bo'yicha tanlash
df.iloc[[0],[0,3,]]  #.iloc yordamida qator va ustunlani ularning tartib raqami bo'yicha tanlash
# df.at[dates[0], "A"] = 0
# df.iat[0, 1] = 0

# df.loc[df['davlat'].isin(['Uzbekistan', 'Hong-Kong', 'Antartica'])]

df_new = df.drop(10) # 10 indeksini o'chiramiz va yangi df yaratamiz
df.drop([15, 20]) # 15 va 20 qatorlarini tashlab yuboramiz

df.drop('Temp', axis=1) # axis=1 ustunni anglatadi, axis=0 esa qatorni
df.drop('Temp', axis='columns')

df.drop('Yil', axis=1, inplace=True) # asl DataFrame o'zgaradi

# 2 ta df ni qo'shish(+).add() ayirish(-).sub() | .rsub() ko'paytirish(*).mul() bo'lish(/).div() mumkin.

# df2.add(df, fill_value=0) fill_value parametri yordamida mos tushuvchi indekslardagi NaN qiymatlarni boshqa qiymat bilan almashtirish

In [ ]:
# pandas Obyekti elementlariga Funksiyalarni qo'llash

df = pd.DataFrame(np.random.randn(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
np.abs(df) # musbat qiymat
np.round(df) # + \ - yaxlitlash
df.mean()

df.apply(np.mean) # Bu metodning afzalligi, o'zingiz istalgan funksiyani yozib uni DF elementlariga qo'llashigniz mumkin.
df.apply(np.sum, axis="columns") # .apply() yordamida funksiyani ustun yoki qatorga qo'llash

# DF qatori max va min qiymati ayirmasini hisoblaydigan funksiya
f = lambda x: x.max() - x.min()
df.apply(f)

# Biror funksiyani DF har bir elementiga alohida qo'llash uchun .applymap()

df = pd.DataFrame(np.arange(1,13).reshape(3,4), index=list('abc'), columns=['Olma','Anor','Qovun','Anjir'])
f = lambda x : x*x # qiymatni kvadratga oshiruvchi funksiya
df.applymap(f)

df.applymap(lambda x : x*x)

import pandas as pd

df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [10, 20, 30]
})

# 1. apply - ustun bo‘yicha o‘rtacha hisoblash
print(df.apply(lambda x: x.mean()))

# 2. applymap - har bir elementga kvadrat
print(df.applymap(lambda x: x**2))

# 3. map - faqat Series (ustun)
print(df['A'].map(lambda x: x * 10))

A     2.0
B    20.0
dtype: float64
   A    B
0  1  100
1  4  400
2  9  900
0    10
1    20
2    30
Name: A, dtype: int64

/tmp/ipykernel_1739/354003402.py:19: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(f)
/tmp/ipykernel_1739/354003402.py:21: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df.applymap(lambda x : x*x)
/tmp/ipykernel_1739/354003402.py:34: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  print(df.applymap(lambda x: x**2))

In [ ]:
# raqamli ustunlarni median qiymat bilan to'ldiramiz

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

cols = df.select_dtypes(include="object").columns

## **Tartiblash va Reytinglash**

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()
obj.sort_values()

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/usa_cars.csv', index_col=0)

df.sort_index()
df.sort_index(axis=1) # ustun nomi bo'yicha tartiblash
df.sort_index(axis=1, ascending=False) # teskari tartiblash
df.sort_values(by='price', ascending=False)
df.sort_values(by=['price','mileage'], ascending=False)
df.head()

# Moshinalarni mileage (yurgan kilometri) bo'yicha reyitnglaymiz
df['rank'] = df['mileage'].rank()
df.sort_values('mileage')

# .rank() method parametri yordamida reyting o'lchash usulini tanlash mumkin (min, max, average, first, dense)
df['rank'] = df['year'].rank(method='average')
df.sort_values('year')

,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition,rank
32,29800,chevrolet,camaro,1973,clean vehicle,46226,red,1q87t3n166389,167763370,pennsylvania,usa,22 hours left,1.0
405,25,ford,door,1984,salvage insurance,41577,white,2ftcf15y9eca14589,167611661,arkansas,usa,17 hours left,2.0
545,0,gmc,door,1993,salvage insurance,0,light blue,1gkfk16k5pj701631,167358601,colorado,usa,18 hours left,3.0
322,0,ford,chassis,1994,salvage insurance,0,green,1fdee14n7rha47894,167359174,california,usa,19 hours left,4.5
362,25,ford,pickup,1994,salvage insurance,206162,white,1ftdf15y2rnb12612,167361489,georgia,usa,2 days left,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1676,23400,ford,fusion,2020,clean vehicle,2452,gray,3fa6p0hd6lr110753,167749593,michigan,usa,21 hours left,2475.5
1642,20600,ford,fusion,2020,clean vehicle,17858,black,3fa6p0cd8lr115427,167570001,virginia,usa,2 days left,2475.5
206,25,chevrolet,vehicl,2020,salvage insurance,7232,black,2gnaxkev6l6128374,167756877,kentucky,usa,3 days left,2475.5
1640,27000,ford,mustang,2020,clean vehicle,12748,red,1fatp8uh3l5101487,167569997,virginia,usa,2 days left,2475.5
1638,20000,ford,fusion,2020,clean vehicle,23984,silver,3fa6p0cd0lr116667,167569992,virginia,usa,2 days left,2475.5

## **Statistik ma'lumotlar**

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/uzbekistan.csv', index_col=0)
df.columns = ['maydoni','aholisi']
# Quyida O'zbekiston Respublikasini maydoni va aholisis sonini ko'rishimiz mumkin
df.sum()

df2 = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/gm_sales.csv", index_col=0)
df2.sum()

df2.sum(axis=1) # yoki axis='columns'

df2.mean(axis=1)

df.idxmin() # min va maximum qiymatlarning indeksini topish
df.idxmax()

df['aholisi'].argmin()
df['maydoni'].argmax() # 8 indexdagi qiymat eng kattasi

df.count() # NaN bo'lmagan qiymatlar soni
df.median() # median qiymat
df.std() # standard deviation
df.cumsum() # kumulativ sum
df.cumprod() # kumulativ product
df.prod()

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv')

# Df ustunlari tarkibi haqida ma'lumot
df.info()

# DF sonli ustunlari haqida statistik ma'lumot
df.describe()

models = df['model'].unique()
models.sort()
print(models)

df['model'].value_counts()

# Korrelyasiya
data = {
    'age':[10,20,30,40,50,60],
    'year':[2010,2000,1990,1980,1970,1960],
}

obj = pd.DataFrame(data)
obj['age'].corr(obj['year'])

obj.value_counts() # Qiymatlar soni

df['year'].corr(df['mileage'])

df = df.drop(['model','transmission','fuelType'] , axis=1)

df['mileage'] = pd.to_numeric(df['mileage'], errors='coerce')

df[['mileage','year','price']].corrwith(df['price']) # price ga nisbatan boshqalarning korrelatsiyasini ko'rish

df.corr()

df.corr(numeric_only=True)

df['year'].value_counts()

df[df.year>2017]

df[df.year== 2020]

# Oddiy Pearson korrelyatsiyasi
# r = np.corrcoef(df['carat'], df['price'])[0, 1]
# print(f"Pearson r = {r:.4f}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13119 entries, 0 to 13118
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   model         13119 non-null  object
 1   year          13119 non-null  int64
 2   price         13119 non-null  int64
 3   transmission  13119 non-null  object
 4   mileage       13119 non-null  int64
 5   fuelType      13119 non-null  object
 6   tax           13119 non-null  int64
 7   mpg           13119 non-null  float64
 8   engineSize    13119 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 922.6+ KB
[' A Class' ' B Class' ' C Class' ' CL Class' ' CLA Class' ' CLC Class'
 ' CLK' ' CLS Class' ' E Class' ' G Class' ' GL Class' ' GLA Class'
 ' GLB Class' ' GLC Class' ' GLE Class' ' GLS Class' ' M Class' ' R Class'
 ' S Class' ' SL CLASS' ' SLK' ' V Class' ' X-CLASS' '180' '200' '220'
 '230']

       year  price  mileage  tax   mpg  engineSize
10     2020  32980      606  145  35.8         2.0
11     2020  26980     1000  145  62.8         1.5
33     2020  28128     2563  145  47.9         1.3
38     2020  31790     3500  145  64.2         2.0
57     2020  48995     3000  145  36.7         2.0
...     ...    ...      ...  ...   ...         ...
13053  2020  27995     2500  145  67.3         1.5
13056  2020  58450     1159  150  32.8         2.9
13113  2020  30999     1000  145  64.2         2.0
13114  2020  35999      500  145  55.4         2.0
13115  2020  24699     2500  145  55.4         2.0

[719 rows x 6 columns]

## **Fayllar bilan ishlash**

https://jovian.com/outlink?url=https%3A%2F%2Fpandas.pydata.org%2Fdocs%2Freference%2Fapi%2Fpandas.read_csv.html  pandasda fayllarni o'qishda 50 ga yaqin parametrlarni ko'rsatish mumkin

In [ ]:
pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/merc.csv", index_col=0) # indexlarni tashlab yuboradi

url = "https://github.com/anvarnarz/praktikum_datasets/blob/main/netflix.xlsx?raw=true"
pd.read_excel(url, index_col='title', nrows=10)  # dastlabki 10 qatorni o'qish va indexni title ustuni qilish

# pd.read_csv('automobile_data.csv', sep=";", index_col=0) # ustunlar orasi ; bilan ajratilganini ko'rsatish

# df = pd.read_excel('uzbekistan.xlsx', names=['huhud','maydon','aholi'], index_col=0) # aloxida ustunlarni ajratib ko'rsatish

df.to_csv("c_data.csv")
obj.to_csv('ay.csv')

pd.read_csv("ay.csv", index_col=0)

df.to_excel("auto_data.xlsx", index=False, columns=['year','tax','mileage','price'])

# HDF5 formatida malumot saqlash
hdfobj = pd.HDFStore("mydata.h5")
hdfobj['cardata'] = df # hdfobj.put('cardata',df)
hdfobj['aydata'] = df2 # hdfobj.put('aydata',df2)
hdfobj['carprice'] = df['price']

hdfobj['cardata']
hdfobj.close()

df.to_hdf('cardata.h5',key='cardata')
data = pd.HDFStore("mydata.h5")
data.keys()

data['cardata'].head()

df = pd.read_hdf('cardata.h5', key='cardata')

df1 = pd.DataFrame({'A': [1, 2, 3]})
df2 = pd.DataFrame({'B': ['a', 'b', 'c']})

with pd.HDFStore('multi_data.h5') as store:
    store.put('first', df1)
    store.put('second', df2)

# O'qib olish
with pd.HDFStore('multi_data.h5') as store:
    print(store['first'])
    print(store['second'])


# html


# json \ pickle

   A
0  1
1  2
2  3
   B
0  a
1  b
2  c

## **Ma'lumotlarni tozalash va tayyorlash**

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)

df.isnull().sum() # NaN qiymatlarining sonini topish
nulls = df.isnull().sum() # NaN qiymatlar soni
rows = df.shape[0] # qatorlar soni
(nulls/rows)*100 # NaN qiymatlarning foizdagi qiymati

df.dropna() # NaN qiymati bor qatorlarni tashlab yuborish
df.dropna(axis=1) # NaN qiymati bor ustunlarni tashlab yuborish

# thresh NaN bo'lmagan qiymatlarining soniga chegara belgilash / subset qaysi ustunlarni tekshirish
# df.dropna(axis=1 , thresh=40,subset=['body-style','length'],inplace=True)  # inplace o'zgarishni saqlash

df.fillna(0) # standart qiymat berish
df.fillna({'wheel-base':90, 'horsepower':100}) # har bir ustunga alohida standart qiymat berish

df[df.company=='audi'].fillna(method='ffill') # method='bfill' NaN qiymatni o'zidan keyingi qiymat bilan to'ldirish

df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill') # asl df ga saqlash

df.fillna(method='ffill', limit=2)

df.fillna({'horsepower':np.mean(df['horsepower']), "wheel-base":np.mean(df['wheel-base'])}) # numpy ning mean funksiyasi orqali to'ldirish

df.fillna(df.mode()[0]) # eng ko'p uchraydigani

df = df.ffill().bfill()

df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')

sum(df2.duplicated()) # takrorlangan qatorlar sonini ko'rish
df2.drop_duplicates() # takrorlangan qatorlarni o'chirish
df2.drop_duplicates(['country','rank'],inplace=True) # takrorlangan qatorlarni ustun bo'yicha topib o'chirish

# reviews[pd.isnull(reviews.country)]

/tmp/ipykernel_1739/3335300202.py:17: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='audi'].fillna(method='ffill') # method='bfill' NaN qiymatni o'zidan keyingi qiymat bilan to'ldirish
/tmp/ipykernel_1739/3335300202.py:19: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill') # asl df ga saqlash
/tmp/ipykernel_1739/3335300202.py:21: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

Outlierlarni olib tashlash uchun ishlatiladi

In [ ]:
Q1 = df['__'].quantile(0.25)
Q3 = df['__'].quantile(0.75)
IQR = Q3 - Q1

# Outlier filtr
mask = (df['__'] >= Q1 - 1.5*IQR) & (df['__'] <= Q3 + 1.5*IQR)
df_clean = df[mask]

# Top 10 SalePrice bilan
top10 = corr['SalePrice'].abs().sort_values(ascending=False).head(11).index
print(top10)

**map(), replace(), rename()** qiymatlarni almashtirish

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)

df['num-of-cylinders'].unique()
cyl_map = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12} # qiymat almashtirish 1- usul
df['cylinders'] = df['num-of-cylinders'].map(cyl_map)

kurs=10720 # 1$=10720 so'm
df['price_uzs'] = df['price'].map(lambda x: x*kurs)

df.replace('five',5,inplace=True)
df.replace(['four','six'],[4,6])
df.replace({'four':4, 'six':6})


df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', index_col='country')

#indeks yoki ustunlar nomiga o'zgartirish
df2.rename(index=str.upper, columns=str.upper) # saqlab qolish uchun inplace=True
df2.rename(index={'Macau':'MAKAO'}, columns={'pop2021':'population'})

df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)

df.price.describe()
bins = [0, 10000, 20000, 50000]
range = pd.cut(df.price, bins)
range.value_counts()

groups = ["arzon", "o'rta", "qimmat"] # guruxlarga nom berish
range = pd.cut(df.price, bins, labels=groups)
range.value_counts()

range = pd.cut(df.price, 3) # teng emas guruxlar
range.value_counts()

range = pd.qcut(df.price, 3) # teng guruxga ajratish
range.value_counts()

df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)

df.groupby('company').price.max() #max narxlarni chiqaramiz

df.groupby('company').agg([len, min, max]) #len - guruhdagi elementlar soni, min - guruh uchun minimum, max - guruh uchun maximum
df.groupby('body-style').price.agg([len, min, max, np.mean]) # agg() istalgancha funksiya chaqirish mumkin
# planets.groupby('method')['year'].describe().unstack()
# df.groupby('key').aggregate(['min', np.median, max])

/tmp/ipykernel_1739/1699084988.py:42: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('company').agg([len, min, max]) #len - guruhdagi elementlar soni, min - guruh uchun minimum, max - guruh uchun maximum
/tmp/ipykernel_1739/1699084988.py:42: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('company').agg([len, min, max]) #len - guruhdagi elementlar soni, min - guruh uchun minimum, max - guruh uchun maximum
/tmp/ipykernel_1739/1699084988.py:43: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.groupby('body-style').price.agg([len, min, max, np.mean]) # agg() istalgancha funksiya chaqirish mumkin
/tmp/ipykernel_1739/1699084988.py:43: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.groupby('body-style').price.agg([len, min, max, np.mean]) # agg() istalgancha funksiya chaqirish mumkin
/tmp/ipykernel_1739/1699084988.py:43: FutureWarning: The provided callable <function mean at 0x7e334a1363e0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.groupby('body-style').price.agg([len, min, max, np.mean]) # agg() istalgancha funksiya chaqirish mumkin

             len      min      max          mean
body-style
convertible    3  13495.0  37028.0  22341.000000
hardtop        2  34028.0  45400.0  39714.000000
hatchback     15   5151.0  16500.0   7159.571429
sedan         32   6575.0  41315.0  17706.333333
wagon          9   6918.0  28248.0  12730.111111

**No-odatiy qiymatlarni topish**

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/MOCK_USER_DATA.csv", index_col=0)

df.describe()

df[(df.age>123) | (df.age<0)] # 123  yoshdan katta qiymatlar bor \ 0 dan kichik

df['age'] = df['age'].apply(np.abs) # 0 dan kichik yoshlar to'g'irlandi
idx = df[df.age>123].index
df.drop(index=idx, inplace=True) # katta qiymatlar tashlab yuborildi
df.describe()

randlist = np.random.permutation(93)
df.take(randlist) # df ni tasodifiy tartibda tahlash

df.sample(5) # tasodifiy qatorlar takrorlanmagan holda chiqadi.
df.sample(10, replace=True) # qatorlar takrorlanadi


df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/blob/main/global_earthquake.csv?raw=true")

df['datetime'] = pd.to_datetime(df['Date'], format="%m/%d/%Y") # datetime ga o'tkazish
df[['datetime']].info()
pd.to_datetime(df['Time'], format="%H:%M:%S")

df['datetime'].dt.weekday.value_counts()


from datetime import datetime
datetime(year=2021, month=7, day=4)

import numpy as np
date = np.array('2021-07-04', dtype=np.datetime64)
date
date + np.arange(12)

dates = pd.to_datetime([datetime(2021, 7, 3), '4th of July, 2021',
                       '2021-Jul-6', '07-07-2021', '20210708'])
dates

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23409 entries, 0 to 23408
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   datetime  23409 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 183.0 KB

DatetimeIndex(['2021-07-03', '2021-07-04', '2021-07-06', '2021-07-07',
               '2021-07-08'],
              dtype='datetime64[ns]', freq=None)

## **`Multi indekslash`** Hierarchical indexing

In [ ]:
data1 = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],[1, 2, 3, 1, 3, 1, 2, 2, 3]]) # irarxik indeksli Ser
data1.index

data1['c':'d'] # c dan d gacha bo'lgan qismin ajratib beradi
data1.loc[:, 2] # barcha 2-indeksdagi ma'lumotlarni ajratib beradi
data1.loc[['b', 'd']] # barcha b va d indeksdagi elementlar

data1.unstack() # sochilgan Ser.ni df ko'rinishida qaytaradi
data1.unstack().stack() # df.ni yi'gilgan Ser.ga o'giradi

arrays = [
    ['2023', '2023', '2024', '2024'],
    ['Yanvar', 'Fevral', 'Yanvar', 'Fevral']
]

index = pd.MultiIndex.from_arrays(arrays, names=('Yil', 'Oy'))

df = pd.DataFrame({'Sotuvlar': [1000, 1500, 2000, 2500]}, index=index)

print(df)


!git clone https://github.com/MansurCompAI/Practicum_Datasets.git # Githubdagi reponi nusxalab oladi
df = pd.read_csv("/content/Practicum_Datasets/world_cities_air_water_quality.csv")

columns = ['City', 'Region', 'Country', 'AirQuality', 'WaterPollution']
df.columns = columns
df['Region'] = df['Region'].map(lambda x: x.replace('"', "")) # Region ustuniga tegishli ma'lumotlardan " belgisini olib tashlash
df['Country'] = df['Country'].map(lambda x: x.replace('"', "")) # Country ustuniga tegishli ma'lumotlardan " belgisini olib tashlash
df['Country'] = df['Country'].map(lambda x: x.strip()) # Country ustuniga tegishli ma'lumotlardan bo'sh belgi(whitespace)ni belgisini olib tashlash

df.to_csv("Updated_dataset.csv", index=False) # faylni saqlab qo'yish

# pd.pivot_table(df, index = ['Country', 'City']) # irarxik indeksli ma'lumotlar to'plamiga o'tish
# pd.DataFrame(df2.values, index = df2.index, columns= [['AIR', 'AIR', 'WATER', 'WATER'], ['AirQuality', 'AirPollution', 'WaterQuality', 'WaterPollution']]) #
# df3.columns.names = ['Object', 'Info'] #irarxik ustunlarga nom berish
# df3.index.names # indeks nomlarini tekshirish
# df3.swaplevel('Country', 'City') # irarxik indekslarni o'rnini almashtiradi
# df3.sort_index(level=0, ascending=False) # indekslarni tartiblash hamda ularning o'rnini almashtirish

!git clone https://github.com/MansurCompAI/Practicum_Datasets.git # Github reponi nusxalab olish

movies = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_movies.csv')
ratings = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_ratings.csv')

movies_ratings = pd.merge(movies, ratings) # umumiy ustun ustida 2 ta datasetni uyg'unlashtirish
extracted = movies_ratings[['title',  'year', 'weighted_average_vote']] # ba'zi ustunlarni ajratib olish

A = pd.DataFrame({'Transport': ['poezd', 'avtomabil', 'kema'],
                  'Tezligi':['70', '180', '45']})
B = pd.DataFrame({'Transport': ['poezd', 'avtomabil', 'tramvay'],
                  'Narxi':['98000', '10000', '65000']})

merged = pd.merge(A, B, how='inner') # inner join - ichki
merged_outer = pd.merge(A, B, how='outer') # outer join - tashqi
merged_left = pd.merge(A, B, how='left') # left join - chap
merged_right = pd.merge(A, B, how='right') # right join - o'ng

merg = pd.merge(A, B, left_on='Transport', right_on='Transport') # yonma yon birlashtirish
A = A.set_index('Transport') #  Transport_turi index qilish
merged1 = pd.merge(A, B, left_index=True, right_on='Transport')
B = B.set_index('Transport')
merged2 = pd.merge(A, B, left_index=True, right_index=True) # Indekslar ustida birlashtirish

# pd.merge(df1, df3, left_on="employee", right_on="name").drop('name', axis=1)
# display('df1a', 'df3', "pd.merge(df1a, df3, left_index=True, right_on='name')")
# df1a.join(df2a)

!git clone https://github.com/MansurCompAI/Practicum_Datasets.git

bank = pd.read_csv("/content/Practicum_Datasets/bank.csv", delimiter=";")
bank1, bank2 = bank[:2521], bank[2521:] # bank ma'lumotlar to'plamini bank1 va bank2 ga bo'lib yuborish
pd.concat([bank1, bank2]) # 2 ta datasetni ulash | axis=1 qilinsa yonma yon ulaydi ||| axis=0 dan tagidan birlashtiradi|

bank1 = bank1.set_index('age') # indeksni o'zgartirish

             Sotuvlar
Yil  Oy
2023 Yanvar      1000
     Fevral      1500
2024 Yanvar      2000
     Fevral      2500
fatal: destination path 'Practicum_Datasets' already exists and is not an empty directory.
fatal: destination path 'Practicum_Datasets' already exists and is not an empty directory.

/tmp/ipykernel_1739/2635376452.py:44: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv('/content/Practicum_Datasets/IMDb/IMDb_movies.csv')

fatal: destination path 'Practicum_Datasets' already exists and is not an empty directory.

In [ ]:
s = pd.Series(['Tom ', ' William Rick', 'John', 'Alber@t'])
print("Split Pattern:")
print(s.str.split(' '))

print(s.str.cat(sep='_'))
print(s.str.get_dummies())
print(s.str.contains(' '))
print(s.str.replace('@','$'))
print(s.str.repeat(2))
print(s.str.count('m'))
print(s.str. startswith ('T'))
print(s.str.find('e'))
print(s.str.swapcase())
print(s.str.isnumeric())

Split Pattern:
0              [Tom, ]
1    [, William, Rick]
2               [John]
3            [Alber@t]
dtype: object
Tom _ William Rick_John_Alber@t
    William Rick  Alber@t  John  Tom
0              0        0     0     1
1              1        0     0     0
2              0        0     1     0
3              0        1     0     0
0     True
1     True
2    False
3    False
dtype: bool
0             Tom
1     William Rick
2             John
3          Alber$t
dtype: object
0                      Tom Tom
1     William Rick William Rick
2                      JohnJohn
3                Alber@tAlber@t
dtype: object
0    1
1    1
2    0
3    0
dtype: int64
0     True
1    False
2    False
3    False
dtype: bool
0   -1
1   -1
2   -1
3    3
dtype: int64
0             tOM
1     wILLIAM rICK
2             jOHN
3          aLBER@T
dtype: object
0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
# df.loc[df['age'] > 25, 'name']
# 25 yoshdan katta odamlarning name ustunini qaytaradi.
# Qaerda ishlatiladi:

# Shart asosida ustun tanlashda.
# Masalan: “30 yoshdan katta mijozlarning ismlari”.'''


# df[df['a'].between(10, 20)]
# Bu kod a ustunidagi qiymatlari 10 dan katta yoki teng va 20 dan kichik yoki teng bo‘lgan qatorlarni qaytaradi.

# Aniq oraliqdagi qiymatlarni ajratib olishda.

# df['text'].str.lower()
# text ustunidagi matnlarni kichik harflarga o‘tkazadi.

# Matnlarni bir xil formatga keltirishda (masalan, "Apple" va "apple" ni teng ko‘rish uchun).

# df[df.duplicated(keep=False)]
#Barcha takroriy qatorlarni (ham birinchisi, ham keyingilari) ajratib oladi. Agar keep=False bo‘lmasa, faqat keyingi nusxalari olinadi.

df['col'].nunique() — col ustunidagi noyob (unique) qiymatlar sonini qaytaradi.

Masalan: agar col = [1, 2, 2, 3] bo‘lsa, .nunique() → 3

df.reset_index() — indeksni oddiy ustunga aylantiradi va yangi default indeks (0,1,2,...) beradi.

df.query("age > 30 and city == 'Tashkent'") — age > 30 va city == 'Tashkent' shartiga mos qatorlarni tanlaydi.
Qaerda ishlatiladi:

Katta hajmdagi ma’lumotdan shartga mos qatorlarni tez ajratib olishda.

df.groupby('city')['income'].max() — har bir shahar uchun income ustunining eng katta qiymatini topadi.
Qaerda ishlatiladi:

Shahar bo‘yicha eng yuqori daromadli mijoz, do‘kon yoki filialni aniqlashda.

df.memory_usage(deep=True)
Nima qiladi:

Har bir ustun Pandas’da qancha xotira (RAM) egallayotganini bayon qiladi.

df['col'].str.contains('apple')
Nima qiladi:

col ustunidagi matnlarda "apple" bor-yo‘qligini tekshiradi.
Natija: True/False bo‘lgan Series qaytaradi.

Matnli ustunlardan ma’lum kalit so‘zlarni filtrlash.

isin() metodi Belgilangan qiymatlar ro‘yxatiga kiruvchi qatorlarni tanlash uchun.

df[df['city'].isin(['Tashkent', 'Samarkand'])]

df da NaN qiymatlar mavjud bo‘lgan qatorlarni olish

df[df.isnull().any(axis=1)]

NaN qiymatlarni ustun bo‘yicha o‘rtacha qiymat bilan to‘ldirish

df.fillna(df.mean(numeric_only=True), inplace=True)

df.drop_duplicates(subset='id', inplace=True)


df.apply(pd.value_counts) value_counts() butun DataFramega

Guruh bo‘yicha birinchi yoki oxirgi qatorni olish

df.groupby('group').first()
df.groupby('group').last()

Yoki .nth(0) va .nth(-1) orqali.

Ustunlar nomidagi bo‘sh joylarni "_" bilan almashtirish

df.columns = df.columns.str.replace(' ', '_')

10 ta eng katta income qiymatga ega qatorlarni chiqarish

df.nlargest(10, 'income')

String ustunlardagi bo‘sh joylarni olib tashlash (har bir qiymat uchun)

df_obj = df.select_dtypes(include='object')

df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())

Faqat sonli ustunlar bo‘yicha o‘rtacha qiymatlarni hisoblash

df.select_dtypes(include='number').mean()

Ustunlarning nomlarini kichik harflarga o‘zgartirish

df.columns = df.columns.str.lower()

df.head() va df.tail():

df.head() – birinchi 5 qatorni ko‘rsatadi.

df.tail() – oxirgi 5 qatorni ko‘rsatadi.

Nimaga kerak:
Ma'lumotni tezda ko‘rib chiqish.

Tahlil qilishdan oldin strukturani tushunish.

Qaerda ishlatiladi:
Ma'lumot yuklab olinganidan keyin formatini tekshirishda.

iloc — raqam orqali (index va ustun raqami).

loc — nom orqali (index nomi va ustun nomi).

Qaerda ishlatiladi:

iloc – indeks tartibida ishlaganda.

loc – aniq ustun va index nomlari bilan ishlaganda.

df[df['age'] > 30] — age ustunidagi 30 dan katta qiymatlarga ega qatorlarni filtrlaydi.

Qaerda ishlatiladi:

Shartli tanlash.
Misol: “30 yoshdan katta mijozlar”.

df['new'] = df['a'] + df['b'] — har bir qator bo‘yicha a va b ustunlarining yig'indisi hisoblanadi va yangi new ustuni hosil bo‘ladi.

Qaerda ishlatiladi:

Yangi ustun yaratishda.
Misol: Narx + Soliq = Umumiy narx.

df.groupby('city').mean() — city bo‘yicha guruhlaydi va har bir guruh uchun o‘rtacha qiymatlarni hisoblaydi.

Qaerda ishlatiladi:

Shaharlar bo‘yicha o‘rtacha narx, yosh, reyting kabi ko‘rsatkichlarni olishda.